// <auto-generated />
using Food_Creator;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Food_Creator.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Food_Creator.Model.Dish", b =>
                {
                    b.Property<int>("DishId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DishId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("DishId");

                    b.ToTable("Dishes");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            Name = "Pizza",
                            Price = 9.99f,
                            Url = "https://pizzapozachodzie.pl/wp-content/uploads/2021/10/pizzeria-template-header-pizza-img.png"
                        },
                        new
                        {
                            DishId = 2,
                            Name = "Burger",
                            Price = 5.99f,
                            Url = "https://www.maxpremiumburgers.pl/globalassets/images/pl-menu/burgery/2024/original_noketchup_singel.jpg?width=1160&sharpen=5&sigma=1,4&threshold=0"
                        });
                });

            modelBuilder.Entity("Food_Creator.Model.DishIngredient", b =>
                {
                    b.Property<int>("DishId")
                        .HasColumnType("int");

                    b.Property<int>("IngredientId")
                        .HasColumnType("int");

                    b.Property<float>("Quantity")
                        .HasColumnType("real");

                    b.HasKey("DishId", "IngredientId");

                    b.HasIndex("IngredientId");

                    b.ToTable("DishIngredients");

                    b.HasData(
                        new
                        {
                            DishId = 1,
                            IngredientId = 1,
                            Quantity = 2f
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 2,
                            Quantity = 1f
                        },
                        new
                        {
                            DishId = 1,
                            IngredientId = 3,
                            Quantity = 3f
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 1,
                            Quantity = 4f
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 4,
                            Quantity = 2f
                        },
                        new
                        {
                            DishId = 2,
                            IngredientId = 5,
                            Quantity = 1f
                        });
                });

            modelBuilder.Entity("Food_Creator.Model.Ingredient", b =>
                {
                    b.Property<int>("IngredientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IngredientId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IngredientId");

                    b.ToTable("Ingredients");

                    b.HasData(
                        new
                        {
                            IngredientId = 1,
                            Name = "Tomato",
                            Price = 0.5f,
                            Url = "https://5.imimg.com/data5/RU/NM/CJ/SELLER-27229577/tomato-500x500.jpg"
                        },
                        new
                        {
                            IngredientId = 2,
                            Name = "Cheese",
                            Price = 1.5f,
                            Url = "https://sklep.spolemkielce.pl/wp-content/uploads/2024/06/ser-z-oczkiem-wloszczowa.jpg"
                        },
                        new
                        {
                            IngredientId = 3,
                            Name = "Basil",
                            Price = 0.2f,
                            Url = "https://p.fide.pl/1600/7/8/78303_veritable_podstawowe_ziola_wklad_nasienny_bazylia.jpg"
                        },
                        new
                        {
                            IngredientId = 4,
                            Name = "Beef 100g",
                            Price = 5f,
                            Url = "https://smakigarwolina.pl/wp-content/uploads/2017/06/wolowina-bez-kosci.jpg"
                        },
                        new
                        {
                            IngredientId = 5,
                            Name = "Bacon 30g",
                            Price = 2.88f,
                            Url = "https://media.istockphoto.com/id/508755080/pl/zdj%C4%99cie/gotowane-plasterki-bekonu-zbli%C5%BCenie-odizolowane-na-na-bia%C5%82e-t%C5%82o.jpg?s=612x612&w=0&k=20&c=SSJBEO0G3F4r83gYWe6zYaKq349RB4J8QyONEyzgJ7c="
                        });
                });

            modelBuilder.Entity("Food_Creator.Model.DishIngredient", b =>
                {
                    b.HasOne("Food_Creator.Model.Dish", "Dish")
                        .WithMany("DishIngredients")
                        .HasForeignKey("DishId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Food_Creator.Model.Ingredient", "Ingredient")
                        .WithMany()
                        .HasForeignKey("IngredientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dish");

                    b.Navigation("Ingredient");
                });

            modelBuilder.Entity("Food_Creator.Model.Dish", b =>
                {
                    b.Navigation("DishIngredients");
                });
#pragma warning restore 612, 618
        }
    }
}
